"""add expires_at, pause_start_time, and total_paused_duration to pomodoro_sessions

Revision ID: 36d27d644fbe
Revises: 1494d893a4ce
Create Date: 2025-08-16 23:08:10.984219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36d27d644fbe'
down_revision: Union[str, Sequence[str], None] = '1494d893a4ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pomodoro_sessions', sa.Column('expires_at', sa.DateTime(), nullable=True))
    op.add_column('pomodoro_sessions', sa.Column('pause_start_time', sa.DateTime(), nullable=True))
    op.add_column('pomodoro_sessions', sa.Column('total_paused_duration', sa.Interval(), nullable=True))
    # Update existing rows with a default value
    op.execute("UPDATE pomodoro_sessions SET total_paused_duration = '0 seconds'")
    # Alter column to set NOT NULL constraint
    op.alter_column('pomodoro_sessions', 'total_paused_duration',
                    existing_type=sa.Interval(),
                    nullable=False,
                    existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pomodoro_sessions', 'total_paused_duration')
    op.drop_column('pomodoro_sessions', 'pause_start_time')
    op.drop_column('pomodoro_sessions', 'expires_at')
    # ### end Alembic commands ###
