"""Add expires_at and remaining_duration_on_pause to pomodoro_sessions

Revision ID: cf363573194d
Revises: 1494d893a4ce
Create Date: 2025-08-16 23:09:51.471570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf363573194d'
down_revision: Union[str, Sequence[str], None] = '1494d893a4ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pomodoro_sessions', sa.Column('expires_at', sa.DateTime(), nullable=True))
    op.add_column('pomodoro_sessions', sa.Column('remaining_duration_on_pause', sa.Interval(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pomodoro_sessions', 'remaining_duration_on_pause')
    op.drop_column('pomodoro_sessions', 'expires_at')
    # ### end Alembic commands ###
