"""add_chat_id_to_pomodoro_sessions

Revision ID: d3f4a3b2c1e0
Revises: 0e5a03fdd37f
Create Date: 2025-08-19 21:01:00.407697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3f4a3b2c1e0'
down_revision: Union[str, None] = '0e5a03fdd37f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pomodoro_sessions', sa.Column('chat_id', sa.Integer(), nullable=True))
    op.execute('UPDATE pomodoro_sessions SET chat_id = 0')
    op.alter_column('pomodoro_sessions', 'chat_id', nullable=False, server_default='0')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pomodoro_sessions', 'chat_id')
    # ### end Alembic commands ###
