"""add escalation_count to reminders

Revision ID: f5e3a8b4c2d1
Revises: e2a5a5f1f1e1
Create Date: 2025-08-20 20:17:21.030205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5e3a8b4c2d1'
down_revision: Union[str, None] = 'e2a5a5f1f1e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reminders', sa.Column('escalation_count', sa.Integer(), nullable=False, server_default=sa.text('0')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reminders', 'escalation_count')
    # ### end Alembic commands ###
